# Generated by Django 5.2 on 2025-04-14 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('columns', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='column',
            name='cards',
        ),
        migrations.DeleteModel(
            name='Card',
        ),
        migrations.AddField(
            model_name='column',
            name='cards',
            field=models.JSONField(default=list),
        ),
    ]
