version: "3.8"

services:
  backend:
    build: ./backend
    ports:
      - "8003:8003"
    environment:
      - DEBUG=1
      - DYNAMODB_ENDPOINT_URL=http://dynamodb-local:8000 # Point to the container name
    depends_on:
      - dynamodb-local

  dynamodb-local:
    image: amazon/dynamodb-local
    ports:
      - "8001:8000"
    command: "-jar DynamoDBLocal.jar -sharedDb"
